[versions]
# Dependencies
kotlin = "1.9.10"
kmmBridge = "0.5.1-SNAPSHOT"
android-gradle-plugin = "8.0.2"
gradle-versions = "0.42.0"
androidx-test-junit = "1.1.5"
junit = "4.13.2"
coroutines = "1.7.3"
kotlinx-datetime = "0.4.0"
ktor = "2.3.3"

stately = "2.0.2"
kermit = "2.0.0-RC3"
skie = "0.4.19"

multiplatformSettings = "1.0.0"
turbine = "1.0.0"
sqlDelight = "2.0.0"

## SDK Versions
minSdk = "21"
targetSdk = "34"
compileSdk = "34"

[libraries]
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

junit = { module = "junit:junit", version.ref = "junit" }

kotlinx-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

multiplatformSettings-common = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatformSettings" }

sqlDelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqlDelight-coroutinesExt = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }

touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
touchlab-stately-common = { module = "co.touchlab:stately-common", version.ref = "stately" }
touchlab-stately-concurrency = { module = "co.touchlab:stately-concurrency", version.ref = "stately" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[bundles]
ktor-common = ["ktor-client-core", "ktor-client-logging", "ktor-client-serialization", "ktor-client-contentNegotiation"]
shared-commonTest = [
    "kotlin-test",
    "multiplatformSettings-test",
    "turbine",
    "coroutines-test",
    "ktor-client-mock"
]
shared-androidTest = [
    "androidx-test-junit",
    "coroutines-test",
    "sqlDelight-jvm"
]

